# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock


title: Sharan Naribole

email: nsharan@rice.edu

description: Blogs about wireless networking research, data science and machine learning projects, work experience and more!

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sharan-naribole.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: nsharan91

github_username:  sharan-naribole

mailto: nsharan@rice.edu

disqus:
    shortname: sharan-naribole
